"""
Generates clean, sanitized .env.example files from scanned codebase or existing .env.
"""

import os
from typing import Dict, List, Optional
from envguard.core.models import ScanCodebaseResult
from envguard.core.parser import parse_env_file, infer_variable_type


def suggest_dummy_value(key: str, inferred_type: Optional[str] = None) -> str:
    """Generate a realistic, safe dummy value based on key name conventions."""
    k = key.upper()

    if k.endswith("_PORT") or k == "PORT":
        return "8000"
    if "DEBUG" in k:
        return "false"
    if k in ("NODE_ENV", "APP_ENV", "ENVIRONMENT", "ENV"):
        return "development"
    if "DATABASE_URL" in k or "DB_URL" in k:
        return "postgresql://postgres:postgres@localhost:5432/app_dev"
    if "MONGO" in k and "URI" in k:
        return "mongodb://localhost:27017/app_dev"
    if "REDIS_URL" in k or "REDIS_HOST" in k:
        return "redis://localhost:6379/0"
    if "HOST" in k:
        return "localhost"
    if "EMAIL" in k or "MAIL" in k:
        return "noreply@example.com"
    if "URL" in k or "ENDPOINT" in k:
        return "http://localhost:3000"
    if any(term in k for term in ("SECRET", "KEY", "TOKEN", "PASSWORD", "PASS", "AUTH")):
        return "your_secret_key_here"
    if any(term in k for term in ("TIMEOUT", "TTL", "MAX", "LIMIT", "COUNT", "RETRY")):
        return "30"

    if inferred_type == "boolean":
        return "false"
    if inferred_type == "integer":
        return "0"
    if inferred_type == "url":
        return "https://api.example.com"

    return f"your_{key.lower()}_here"


def generate_env_example(
    scan_result: Optional[ScanCodebaseResult] = None,
    source_env_path: Optional[str] = None,
    output_path: Optional[str] = None,
) -> str:
    """
    Generate the contents of a sanitized .env.example file.
    Optionally write directly to output_path.
    """
    lines: List[str] = [
        "# ===================================================================",
        "# Generated by EnvGuard - Open Source Environment Governance Suite",
        "# Copy this file to .env and replace dummy values with your config.",
        "# ===================================================================",
        "",
    ]

    var_dict: Dict[str, dict] = {}

    # Source 1: Parse existing source .env if given
    if source_env_path and os.path.exists(source_env_path):
        env_file = parse_env_file(source_env_path)
        for k, v in env_file.variables.items():
            dummy = suggest_dummy_value(k, v.inferred_type)
            var_dict[k] = {
                "value": dummy,
                "type": v.inferred_type,
                "comment": v.comment or f"Type: {v.inferred_type}",
            }

    # Source 2: Discovered from codebase scan
    if scan_result and scan_result.variables:
        for k, refs in scan_result.variables.items():
            if k not in var_dict:
                dummy = suggest_dummy_value(k)
                first_ref = refs[0]
                var_dict[k] = {
                    "value": dummy,
                    "type": "string",
                    "comment": f"Used in {first_ref.file_path}:{first_ref.line_number}",
                }

    # Format sorted variables
    for key in sorted(var_dict.keys()):
        data = var_dict[key]
        val = data["value"]
        comment = data.get("comment")
        if comment:
            lines.append(f"# {comment}")
        lines.append(f"{key}={val}")
        lines.append("")

    content = "\n".join(lines)

    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

    return content
